on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: Job that says hello
    steps:
      - name: Hello world step
        id: hello
        uses: amalej/github-action-first@v1.0.6
        with:
          who-to-greet: 'Alejandro Marco'
      - name: Get the output
        run: echo "The time was ${{ steps.hello.outputs.GITHUB_OUTPUT }}"