on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: Job that says hello
    steps:
      - name: Log
        env:
          DUMMY_KEY: ${{ secrets.DUMMY_KEY }};
      - name: Log
        run: echo "value is ${process.env.DUMMY_KEY}";
      - name: Hello world step
        id: hello
        uses: amalej/github-action-first@v1.0.7
        with:
          who-to-greet: 'Alejandro Marco'
      - name: Get the output
        run: echo "The time was ${{ steps.hello.outputs.time }}"
